name: Deploy GCP Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build and push Docker image for demo portal
        env:
          PROJECT_ID: ${{ secrets.TF_VAR_project_id }}
        run: |
          echo "Writing service account key to file..."
          printf '%s' "${{ secrets.GCP_CREDENTIALS }}" | python -m json.tool > key.json
          echo "Logging into gcr.io..."
          docker login -u _json_key --password-stdin https://gcr.io < key.json
          echo "Building Docker image..."
          docker build -t gcr.io/${PROJECT_ID}/demo-portal:latest .
          echo "Pushing Docker image..."
          docker push gcr.io/${PROJECT_ID}/demo-portal:latest

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Run tfsec Security Scan
        working-directory: terraform
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec . --soft-fail

      - name: Run Checkov Security Scan
        working-directory: terraform
        run: |
          pip install checkov
          checkov -d . --quiet || true

      - name: Initialize Terraform
        working-directory: terraform
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_sa_display_name: ${{ secrets.TF_VAR_sa_display_name }}
          TF_VAR_tenant: ${{ secrets.TF_VAR_tenant }}
          TF_VAR_demo_portal_image_url: "gcr.io/${{ secrets.TF_VAR_project_id }}/demo-portal:latest"
        run: terraform init

      - name: Plan Terraform Changes
        working-directory: terraform
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_sa_display_name: ${{ secrets.TF_VAR_sa_display_name }}
          TF_VAR_tenant: ${{ secrets.TF_VAR_tenant }}
          TF_VAR_demo_portal_image_url: "gcr.io/${{ secrets.TF_VAR_project_id }}/demo-portal:latest"
        run: terraform plan

#      - name: Apply Terraform Changes
#        if: github.ref == 'refs/heads/main'
#        working-directory: terraform
#        env:
#          TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
#          TF_VAR_region: ${{ secrets.TF_VAR_region }}
#          TF_VAR_sa_display_name: ${{ secrets.TF_VAR_sa_display_name }}
#          TF_VAR_tenant: ${{ secrets.TF_VAR_tenant }}
#          TF_VAR_demo_portal_image_url: "gcr.io/${{ secrets.TF_VAR_project_id }}/demo-portal:latest"
#        run: terraform apply -auto-approve
